# Generated by Django 4.1.4 on 2023-01-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_email_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
