# Generated by Django 4.1.4 on 2023-01-01 13:44

import datetime
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverification_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 13, 44, 47, 570474, tzinfo=datetime.timezone.utc)),
        ),
    ]
