# Generated by Django 4.1.4 on 2023-01-02 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_emailverification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 16, 5, 12, 584884, tzinfo=datetime.timezone.utc)),
        ),
    ]
