# Generated by Django 4.1.4 on 2023-01-03 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_emailverification_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 16, 28, 16, 551874, tzinfo=datetime.timezone.utc)),
        ),
    ]
